# Generated by Django 3.0.5 on 2020-04-13 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('reduced_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('full_name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=64)),
                ('spanish_title', models.CharField(max_length=64)),
                ('english_title', models.CharField(max_length=64)),
                ('poster', models.ImageField(height_field=100, upload_to='images', width_field=100)),
                ('actors', models.ManyToManyField(to='movies.Participant')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to='movies.Participant')),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('languages', models.ManyToManyField(to='movies.Language')),
            ],
        ),
    ]
