# Generated by Django 3.0.5 on 2020-04-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='english_title',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, height_field=100, upload_to='images', width_field=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='spanish_title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
