# Generated by Django 3.0.5 on 2020-04-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200414_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rotten_rating',
            field=models.IntegerField(default=0),
        ),
    ]
